/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Recipe;
import model.Weekday;

/**
 *
 * @author Jonas
 */
public class WeekdayPanel extends javax.swing.JPanel {

    private Weekday wkday;
    private Recipe weekRecipe;
    private GUI gui;

    /**
     * Creates new form WeekdayPanel
     */
    public WeekdayPanel(GUI gui, Weekday wkday) {
        this.gui = gui;
        this.wkday = wkday;
        weekRecipe = wkday.getRecipe();
        initComponents();
        setSize(142, 400);
        setWeekday();
        setColors(GUI.weekPanelColor);
    }

    public void setColors(Color col) {
        jLabelDescription.setBackground(col);
        jPanel1.setBackground(col);
    }

    public void setWeekday() {
        jLabelDay.setText(wkday.getWeekName());
        jLabelDate.setText("<html>" + wkday.getDate() + "</html>");
        jLabelDescription.setText(getWeekRecipe().getDescription());
        jLabelOpskriftNavn.setText("<html>" + getWeekRecipe().getName() + "</html>");
        jLabelCookingTime.setText(getWeekRecipe().getCookingtime() + " min");
        jLabelPortions.setText(getWeekRecipe().getPortions() + "");
        if (!wkday.getRecipe().isActive()) {
            disableButtons();
        }
        if (wkday.isOmit() && wkday.getRecipe().isActive()) {
            jButtonDisable.setText("Genaktiver");
        }
    }

    public Recipe getWeekRecipe() {
        return wkday.getRecipe();
    }

    public void switchDay() {
        int swap = GUI.getCh().getWdh().switchDays(wkday);
        if (swap == 0) {
            setColors(GUI.daySwitchColor);
        }
        if (swap == 1) {
            setColors(GUI.weekPanelColor);
        }
        if (swap == 2) {
            gui.changeTo(gui.getSelectedWeekPanel());
        }
    }

    public void draw(Graphics g) {
        if (!wkday.getRecipe().isActive()) {
            Image img = Toolkit.getDefaultToolkit().getImage("src\\view\\images\\deletedred.png");
            g.setColor(GUI.deletedColor);
            g.fillRect(0, 0, getWidth(), getHeight());
            g.drawImage(img, ((getWidth() / 2) - (img.getWidth(this) / 2)), ((getHeight() / 2) - (img.getHeight(this) / 2)), this);
            setColors(GUI.omittedColor);
        }
        if (wkday.isOmit() && jPanel1.getBackground() != GUI.daySwitchColor) {
            setColors(GUI.omittedColor);
        }
    }

    public void disableButtons() {
        jButtonDisable.setEnabled(false);
        jButtonReplace.setEnabled(false);
    }

    public void toggleOmit() {
        if (wkday.isOmit()) {
            setColors(GUI.weekPanelColor);
            wkday.setOmit(false);
            jButtonDisable.setText("Undlad");
        } else {
            setColors(GUI.omittedColor);
            wkday.setOmit(true);
            jButtonDisable.setText("Genaktiver");
        }
        try {
            GUI.getCh().getDbh().updateWeekdayOmit(wkday);
        } catch (SQLException ex) {
            System.out.println("FEJL VED OPDATERING AF OMIT PÅ WEEKDAY" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                draw(g);
            }
        };
        jLabelOpskriftNavn = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCookingTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPortions = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JTextArea();
        jButtonReplace = new javax.swing.JButton();
        jButtonDisable = new javax.swing.JButton();

        setBackground(new java.awt.Color(105, 135, 186));

        jPanel1.setBackground(GUI.dayColor);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jLabelOpskriftNavn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelOpskriftNavn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpskriftNavn.setText("Stor fed skinke");

        jLabelDay.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        jLabelDay.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay.setText("Mandag");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tilberedning:");

        jLabelCookingTime.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabelCookingTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCookingTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCookingTime.setText("30 min");
        jLabelCookingTime.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Antal personer");

        jLabelPortions.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabelPortions.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPortions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPortions.setText("4");

        jLabelDate.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("06-04-2015");

        jLabelDescription.setEditable(false);
        jLabelDescription.setBackground(GUI.dayColor);
        jLabelDescription.setColumns(20);
        jLabelDescription.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setLineWrap(true);
        jLabelDescription.setRows(1);
        jLabelDescription.setToolTipText("<html><p width=\"300\">" +wkday.getRecipe().getDescription()+"</p></html>");
        jLabelDescription.setWrapStyleWord(true);
        jLabelDescription.setAutoscrolls(false);
        jLabelDescription.setBorder(null);
        jLabelDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDescription.setFocusable(false);
        jLabelDescription.setOpaque(false);
        jLabelDescription.setRequestFocusEnabled(false);
        jLabelDescription.setVerifyInputWhenFocusTarget(false);
        jLabelDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelDescriptionMouseReleased(evt);
            }
        });

        jButtonReplace.setBackground(GUI.replaceDayColor);
        jButtonReplace.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonReplace.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReplace.setText("Udskift");
        jButtonReplace.setBorder(null);
        jButtonReplace.setBorderPainted(false);
        jButtonReplace.setFocusPainted(false);
        jButtonReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReplaceActionPerformed(evt);
            }
        });

        jButtonDisable.setBackground(GUI.disableDayColor);
        jButtonDisable.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonDisable.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDisable.setText("Undlad");
        jButtonDisable.setBorder(null);
        jButtonDisable.setBorderPainted(false);
        jButtonDisable.setFocusPainted(false);
        jButtonDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonReplace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelOpskriftNavn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelPortions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCookingTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonDisable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelDay)
                .addGap(6, 6, 6)
                .addComponent(jLabelDate)
                .addGap(0, 0, 0)
                .addComponent(jLabelOpskriftNavn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelPortions))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCookingTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonDisable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReplaceActionPerformed
        //GENERER DENNE DAG IGEN
    }//GEN-LAST:event_jButtonReplaceActionPerformed

    private void jButtonDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisableActionPerformed
        toggleOmit();
    }//GEN-LAST:event_jButtonDisableActionPerformed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        switchDay();
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jLabelDescriptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDescriptionMouseReleased
        switchDay();
    }//GEN-LAST:event_jLabelDescriptionMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDisable;
    private javax.swing.JButton jButtonReplace;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCookingTime;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JTextArea jLabelDescription;
    private javax.swing.JLabel jLabelOpskriftNavn;
    private javax.swing.JLabel jLabelPortions;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
